name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start database
        run: docker-compose up -d

      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0

        with:
          distribution: 'corretto'
          java-version: '19'

      - name: Run tests
        run: ./gradlew test
        env:
          DB_PORT: 5432
          DB_DATABASE: my_store
          DB_USER: osmait
          DB_PASSWORD: admin123
          DB_HOSTNAME: localhost

